### ISSUE TITLE
Problem with building WoodCutter

### ISSUE THREAD

**Issue by AndusDEV** [enjikaka/WoodCutter#5]
[WARNING] Some problems were encountered while building the effective model for se.enji:WoodCutter:jar:1.5.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for me.botsko:prism:jar should not point at files within the project directory, ${basedir}/lib/prism-2.0.6.jar will be unresolvable by dependent projects @ line 49, column 25

**Comment by AndusDEV** [comment]
Hello?

**Comment by enjikaka** [comment]
Builds fine for me and the provided build on https://dev.bukkit.org/projects/woodcutter is still working on the latest server version.
